# version: 2.1
# executors:
#   node:
#     docker:
#       - image: circleci/node:10
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build:
#         branches:
#           only:
#             - circleci-project-setup
#
# #jobs details
# jobs:
#   build:
#     steps:
#       - checkout
#       - run: ls
#       - run: pwd
#

version: 2.1
workflows:
  version: 2
  build_and_test:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: pwd
