version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10

workflows:
  version: 2
  main_flow:
    jobs:
      - unit-test
      - build-image:
          requires:
            - unit-test
      - deploy-to-test-cluster:
          requires:
            - build-image

jobs:
  unit-test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v0-deps-{{ checksum "package.json" }}
            - v0-deps-
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v0-deps-{{ checksum "package.json" }}
      - run:
          command: node app
          background: true
      - run: while ! nc -z localhost 8080 ; do sleep 1 ; done
      - run: curl localhost:8080

  build-image:
    executor: node
    steps:
      - run: docker ps
      - run : echo "finished building and uploading docker image"

  deploy-to-test-cluster:
    executor: node
    steps:
      - run : echo "finished deploying to cluster"
