version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10

workflows:
  version: 2
  main_flow:
    jobs:
      - test

jobs:
  test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v0-deps-{{ checksum "package.json" }}
            - v0-deps-
      - run: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v0-deps-{{ checksum "package.json" }}
      - run:
          command: node app
          background: true
      - run: sleep 5
      - run: curl localhost:8080
